doctrine:
    dbal:
        default_connection: postgres
        connections:
#            mysql:
#                driver: 'pdo_mysql'
#                server_version: '5.7'
#                charset: utf8mb4
#                default_table_options:
#                    charset: utf8mb4
#                    collate: utf8mb4_unicode_ci
#                url: '%env(resolve:MYSQL_DATABASE_URL)%'
            sphinx:
                driver: 'pdo_mysql'
                url: '%env(resolve:SPHINX_DATABASE_URL)%'

            postgres:
                driver: 'pdo_pgsql'
                server_version: '9.2'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
                url: '%env(resolve:PGSQL_DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: postgres
        entity_managers:
#            mysql:
#                connection: mysql
#                naming_strategy: doctrine.orm.naming_strategy.underscore
#                auto_mapping: true
#                mappings:
#                    App:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity'
#                        prefix: 'App\Entity'
#                        alias: App
            sphinx:
                connection: sphinx
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Sphinx'
                        prefix: 'App\Entity\Sphinx'
                        alias: App

            postgres:
                connection: postgres
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App